DELTA_TIME = 1
TIME_STEPS = 2000
#FORCE_MAGNIFIER = 1
#SPEED_MAGNIFIER = 0.12
MASS_MAGNIFIER = 9000000000

INTEGRATION_OPTIONS = ["Leap_Frog","LF_K&D","Euler","Semi_Impl_Euler","Verlet","Vel_Verlet","Vel_Verlet2"]
INTEGRATION_CHOICE = "Vel_Verlet2"

PRESETS = ["3_Body_Problem","100_Astroids_and_Sun"]
PRESET_CHOICE = "100_Astroids_and_Sun"

DRAW_OCTTREE_BOXES = False
DRAW_BOX_MASS = False
WRITE_TO_VTU = False

SIZE = 80
MARKERSIZE_MULTIPLIER = 10

GRAV_CONST = 6.674e-11
MAX_DEPTH = 20
CAPACITY = 10
THRESHOLD = 0.5

TIME_BETWEEN_FRAMES = 0.01